version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /.docker
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /pzzld
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /bin/api
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /bin/cli
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /crates/core
    schedule:
      interval: weekly
